---
- name: Install and Configure WordPress
  hosts: all
  become: true
  vars:
    mysql_root_password: "your_root_password"
    wordpress_db_name: "wordpress"
    wordpress_db_user: "wp_user"
    wordpress_db_password: "wp_password"
    wordpress_url: "https://wordpress.org/latest.tar.gz"
    wordpress_install_dir: "/var/www/html/wordpress"

  tasks:
    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
          - unzip
          - curl
          - wget
          - mysqlclient
          - pymysql
        state: present


    - name: Start and enable Apache and MySQL
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mysql

    - name: Secure MySQL installation (set root password)
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        host_all: yes
        priv: '*.*:ALL,GRANT'
        state: present

    - name: Create WordPress database
      mysql_db:
        name: "{{ wordpress_db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create WordPress database user
      mysql_user:
        name: "{{ wordpress_db_user }}"
        password: "{{ wordpress_db_password }}"
        priv: "{{ wordpress_db_name }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Download WordPress
      get_url:
        url: "{{ wordpress_url }}"
        dest: "/tmp/wordpress.tar.gz"

    - name: Extract WordPress
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/html/"
        remote_src: yes

    - name: Set correct permissions
      file:
        path: "{{ wordpress_install_dir }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Create WordPress config file
      template:
        src: wordpress-config.php.j2
        dest: "{{ wordpress_install_dir }}/wp-config.php"

    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted

    - name: Open firewall for HTTP and HTTPS
      ufw:
        rule: allow
        name: "{{ item }}"
      loop:
        - Apache
        - Apache Secure

  handlers:
    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted
